name: Build Docker

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t box-skeleton . --build-arg version=develop
          docker run --entrypoint /bin/sh --name box box-skeleton
          docker cp box:/opt/www/box.macos.arm64 .
          docker cp box:/opt/www/box.macos.x86_64 .
          docker cp box:/opt/www/box.linux.x86_64 .
      - name: Rename
        run: |
          mv box.macos.arm64 sgit.darwin.arm64
          mv box.macos.x86_64 sgit.darwin.x86_64
          mv box.linux.x86_64 sgit.linux.x86_64
      - name: Upload artifact for sgit
        uses: actions/upload-artifact@v3
        with:
          name: sgit.darwin.arm64
          path: sgit.darwin.arm64
      - name: Upload artifact for sgit
        uses: actions/upload-artifact@v3
        with:
          name: sgit.darwin.x86_64
          path: sgit.darwin.x86_64
      - name: Upload artifact for sgit
        uses: actions/upload-artifact@v3
        with:
          name: sgit.linux.x86_64
          path: sgit.linux.x86_64
